### PR TITLE
Fix memory leak if reading stream for image failed

### PR DESCRIPTION
**Pull request by philippwiesemann**
If an error occurred while reading a thumbnail image from its stream then the allocated buffer was not deleted. This was fixed by using a smart pointer which will always delete the buffer later.

Thanks!

### CODE REVIEW

**Comment by palinek** [comment]
GTM

**Comment by paulolieuthier** [comment]
The image may be still used after the end of the function. Are you sure we should delete the buffer? From the [docs](http://doc.qt.io/qt-5/qimage.html#QImage-3):

> The buffer must remain valid throughout the life of the QImage and all copies that have not been modified or otherwise detached from the original buffer.

We must provide a cleanup function, since QImage destructor won't delete it.

**Comment by philippwiesemann** [comment]
The documentation for `loadFromData()` does not have this note.

**Comment by paulolieuthier** [comment]
You are correct.

**Pull request merged**
