### PR TITLE
 iconinfo: Properly handle multiple names

### PR DESCRIPTION
**Pull request by palinek**

### CODE REVIEW

**Comment by palinek** [comment]
Warning: this breaks ABI & API

**Comment by tsujan** [comment]
This seems interesting but should be checked and tested under various circumstances. I hope there's no haste here.

**Comment by palinek** [comment]
> should be checked and tested under various circumstances

Definitely...

**Comment by tsujan** [comment]
This and, especially, the removal of `IconTheme` looks more logical than before.

GTM.

**Comment by agaida** [comment]
GTM

**Pull request merged**
