### PR TITLE
Use lxqt compiler settings

### PR DESCRIPTION
**Pull request by luis-pereira**
@PCMan Can you pls take a look at https://github.com/lxde/libfm-qt/commit/eab53132431899bf8a944a4948ab0abf9b655847 ? You know the code better.

### CODE REVIEW

**Comment by tsujan** [comment]
@luis-pereira 
Theoretically speaking, https://github.com/lxde/libfm-qt/commit/eab53132431899bf8a944a4948ab0abf9b655847 seems more appropriate to me.

**Comment by luis-pereira** [comment]
@tsujan If FTBFS without https://github.com/lxde/libfm-qt/commit/eab53132431899bf8a944a4948ab0abf9b655847 because of https://github.com/lxde/liblxqt/blob/master/cmake/modules/LXQtCompilerSettings.cmake#L68.

**Comment by tsujan** [comment]
@luis-pereira 
On second thought, maybe `toUtf8()` is needed there because of "copy\n".

**Comment by luis-pereira** [comment]
@tsujan converting "copy\n" to UTF-8 it's a no operation as it's US-ASCII/Latin-1 encoded. The issue might be in `urilist`. What's `urilist` encoding ?

**Comment by tsujan** [comment]
We have `data->setData("text/uri-list", urilist);` below it, so if you're sure that there's no need to convert "copy\n" to UTF-8, the commit couldn't do any harm.

**Comment by tsujan** [comment]
@luis-pereira 
The hierarchy is

`fm_path_list_to_uri_list() → fm_path_list_write_uri_list() → fm_path_to_uri() → fm_path_to_str() and g_filename_to_uri()`

which means it consists of escaped ASCII-encoded URIs, with the components following Section 3.3. of RFC 2396 (https://developer.gnome.org/glib/stable/glib-URI-Functions.html#g-filename-to-uri).

**Comment by luis-pereira** [comment]
@tsujan Thaks for the digging. So, there is no doubt, it's good to go.

**Comment by tsujan** [comment]
> So, there is no doubt, it's good to go.

Yes, it is :)

**Comment by paulolieuthier** [comment]
GTM.

**Comment by luis-pereira** [comment]
@tsujan @paulolieuthier This commit will make a lot of warning popup. Hoping to fix them before the release.

**Comment by tsujan** [comment]
> This commit will make a lot of warning popup. Hoping to fix them before the release.

I'll also check them tomorrow.

**Comment by luis-pereira** [comment]
@tsujan That's great.

**Pull request merged**
