### PR TITLE
Build system

### PR DESCRIPTION
**Pull request by luis-pereira**
Add the ability to use find_package().

### CODE REVIEW

**Comment by PCMan** [comment]
Cool! Thank you very much.
I just tried to work on CMake exports yesterday and I had no idea how to make it work.
So I use pkgconfig for now.

**Comment by PCMan** [comment]
BTW, I'd like to rename the library to libfm-qt and remove the qt5 suffix since we only support qt5 now.

**Comment by jleclanche** [comment]
@PCMan agreed, go for it.

**Comment by luis-pereira** [comment]
@PCMan Don't worry about it. I'm taking care of it.

**Comment by luis-pereira** [comment]
@PCMan Done. No superbuild support yet. There are still improvements to be done. But it's ready to merge. Pls test.

**Pull request merged**
