### PR TITLE
Fix detailed list crash on double clicking folders

### PR DESCRIPTION
**Pull request by tsujan**
Tries to fix https://github.com/lxde/pcmanfm-qt/issues/458

### CODE REVIEW

**Comment by agaida** [comment]
GTM

**Comment by tsujan** [comment]
@agaida You mean that, like me, you saw the crash but after this it doesn't occur?

**Comment by agaida** [comment]
you shouldn't haved ask - tried it another ten times, was about to give it up - and it crashed again

**Comment by tsujan** [comment]
Ha ha. I used it more than 30 times and didn't see a crash. But logically, it should have no effect.

I don't close it; it might be changed to a real fix later.

**Comment by agaida** [comment]
my fault - don't restarted the second test machine after installing the fixed packages - so the old pcmanfm-qt was running ,,,

**Comment by tsujan** [comment]
> i would tend to ship it

It's completely harmless as we don't have tree expanding in the folder view. If it has effect, that might be because of a Qt bug, which is worked around in this way.

**Comment by agaida** [comment]
ok, works without any negative impact and does what it should to. GTM

**Pull request merged**
