### PR TITLE
Remove empty files

### PR DESCRIPTION
**Pull request by jubalh**
All of these header files are empty. I don't see why and where they are
needed.

### CODE REVIEW

**Comment by palinek** [comment]
Indeed... but IMO @PCMan should have a look and say if these files are present intentionaly.

**Comment by tsujan** [comment]
GTM.

Perhaps these empty files were created because of an old plan that wasn't followed later.

**Comment by paulolieuthier** [comment]
They were probably auto generated, I believe @PCMan used some tool to ease the porting process.

**Comment by PCMan** [comment]
Yes, it's safe to remove them.
They are automatically generated by my C to C++ wrapper script.
The original plan was to add the wrappers manually to these files, but I'm don't have the time to do it.
Please feel free to delete them. Thanks!

**Comment by palinek** [comment]
landed in @a421dbd, thanks

**Pull request closed without merging**
