### PR TITLE
Fix Custom Actions Submenu

### PR DESCRIPTION
**Pull request by tsujan**
Fixes https://github.com/lxde/lxqt/issues/1135

A screenshot:

submenu

### CODE REVIEW

**Comment by tsujan** [comment]
Please see http://www.nautilus-actions.org/?q=node/377 for a detailed explanation of how to create custom actions in submenus. The custom actions folder is `~/.local/share/file-manager/actions`.

**Comment by tsujan** [comment]
For some reason unknown to me, https://github.com/lxde/lxqt/issues/1135 is deleted. So, I briefly describe the issue that's fixed by this PR:

Custom actions can be grouped on a submenu but only one of them was shown before. The cause was that separate submenus were created per action in the code (a typo?).

**Comment by paulolieuthier** [comment]
GTM.

**Comment by agaida** [comment]
GTM

**Pull request merged**
